### ISSUE TITLE
Add config option for additional WP API fields

### ISSUE THREAD

**Issue by mjanos10** [tnguyen14/tobiko#27]
Hi!

I love your work, finally I have found a straightforward static site generator that can work with the WP API! I have an enhancement request, though.

It would be cool, if we could set additional API fields that the plugin could return to us to our templates.
So for example in your `wordpress.js` file you have the followings:

```js
function getEndpoint (endpoint, apiRoot) {
	let postsPerPage = 100;
	let page = 1;
	return getPosts(apiRoot + '/' + endpoint.postType, postsPerPage, page, [])
		.then((posts) => {
			return posts.reduce(function (_posts, p) {
				_posts[p.slug] = {
					'index': {
						date: p.date,
						updated: p.modified,
						template: endpoint.template,
						title: p.title.rendered,
						main: p.content.rendered,
						slug: p.slug,
						filepath: endpoint.folder + '/' + p.slug + '/index',
						filename: 'index'
					}
				};
				return _posts;
			}, {});
		});
}
```
If I want to get for example the excerpt of a post I have to manually edit this file. It would be nice if we could do that when initializing tobiko with the wordpress plugin, with something like this:

```js
tobiko({
  // ...
  plugins: {
    wordpress: {
      apiRoot: 'http://acelszerkezet-local.hu/wp-json/wp/v2',
      contents: [
        {
          postType: 'posts',
          folder: 'blog',
          template: 'article.hbs',
          custom_restfield: [
            'excerpt', 'guid', 'modified'
          ]
        },
        {
          postType: 'portfolio',
          folder: 'portfolio',
          template: 'portfolio.hbs',
          custom_restfield: [
            'my_custom_featured_img_restfield'
          ]
        }
      ]
    },
  }
})
```

**Comment by tnguyen14** [comment]
Hi! Thanks so much for your comment! 

My apologies for not responding earlier. For some reason I don't get email for issues.

Just so I understand your request correctly, you're asking to pass a list of custom fields to the WP REST API call, so its responses can be added to the content? 

If so, this seems very reasonable. Let me take a stab at it and let you know. I might need your help testing it though, as I don't have a WP instance with custom field set up ready to go. Would you be available for that?

**Comment by tnguyen14** [comment]
Hi, I was looking into this, and the API does not have the option to specify which fields to retrieve back. However, that is something you can customized on the WordPress end. Here's a guide on how you can add a WP filter to do so https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/

I hope that's helpful.
